print("Welcome to the Letter Counter App")
name = input("What is your name:  ")
print(f"{name}")
message = input("Please enter a message ")
print(f"{message}")
letter = input("Which letter would you like to count the occurrences of: ")
print(f"{letter}")
contar = message.count(letter)
print(f"{contar}")